ltx2_checkpoint = "E:\\ComfyUI\\ComfyUI\\models\\checkpoints\\LTX-2\\ltx-2.3-22b-dev.safetensors"
output_dir = "./outputs"
output_name = "ltx2_lora"
dataset_config = "dataset_ltx2.toml"
gemma_safetensors = "E:\\ComfyUI\\ComfyUI\\models\\text_encoders\\gemma_3_12B_it_fp8_scaled.safetensors"
ltx_mode = "video"
lora_target_preset = "t2v"
network_module = "networks.lora_ltx2"
network_dim = 16
network_alpha = 16.0
network_args = [ "loraplus_lr_ratio=4",]
max_train_epochs = 50
max_train_steps = 5000
train_batch_size = 1
seed = 1026
gradient_checkpointing = true
gradient_accumulation_steps = 1
guidance_scale = 1.0
mixed_precision = "bf16"
ltx_version = "2.3"
ltx_version_check_mode = "warn"
fp8_base = true
fp8_scaled = true
flash_attn = true
blocks_to_swap = 20
use_pinned_memory_for_block_swap = true
learning_rate = 0.0001
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 50
timestep_sampling = "shift"
discrete_flow_shift = 3.0
optimizer_type = "AdamW8bit"
optimizer_args = [ "weight_decay=0.01", "betas=(0.9, 0.999)",]
save_every_n_steps = 250
log_with = "tensorboard"
logging_dir = "./logs"
persistent_data_loader_workers = true
cuda_allow_tf32 = true
cuda_cudnn_benchmark = true
